// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdn1eF11_qEIvktvQjTdrbmGzxwlK1jXY',
    appId: '1:229417490817:web:0e25dd18f490acd8083080',
    messagingSenderId: '229417490817',
    projectId: 'seizure-alert-app',
    authDomain: 'seizure-alert-app.firebaseapp.com',
    storageBucket: 'seizure-alert-app.firebasestorage.app',
    measurementId: 'G-3MLCNQ4P2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwFJCEpCkmo817CJ0A6G6AsjS1WraS59k',
    appId: '1:229417490817:android:8d88565347f3d201083080',
    messagingSenderId: '229417490817',
    projectId: 'seizure-alert-app',
    storageBucket: 'seizure-alert-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjmvEkoovhSKcJx-lTJRME6Aa5jcqCsMs',
    appId: '1:229417490817:ios:41acf835466ba835083080',
    messagingSenderId: '229417490817',
    projectId: 'seizure-alert-app',
    storageBucket: 'seizure-alert-app.firebasestorage.app',
    iosBundleId: 'com.darren.potts.seizureApp',
  );
}
